[project]
name = "harvest"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.farm]
path = "contracts/farm.clar"
depends_on = []
